// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCATn7lwg2x5kxEkfrGpW4UbRlc7KpHEDg',
    appId: '1:100060804942:web:3b7e88d9261d4cb6a4901f',
    messagingSenderId: '100060804942',
    projectId: 'upload-92830',
    authDomain: 'upload-92830.firebaseapp.com',
    databaseURL: 'https://upload-92830-default-rtdb.firebaseio.com',
    storageBucket: 'upload-92830.appspot.com',
    measurementId: 'G-1ZGTVPHKL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIwQAokScBCg-uycT5uUaNswM4JmmULEc',
    appId: '1:100060804942:android:9440deeac6d56fb0a4901f',
    messagingSenderId: '100060804942',
    projectId: 'upload-92830',
    databaseURL: 'https://upload-92830-default-rtdb.firebaseio.com',
    storageBucket: 'upload-92830.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCE1aTHT8YdKfFm_C5fmY9Ta-zfdNx5Xg',
    appId: '1:100060804942:ios:c3ad2c75d469f1d1a4901f',
    messagingSenderId: '100060804942',
    projectId: 'upload-92830',
    databaseURL: 'https://upload-92830-default-rtdb.firebaseio.com',
    storageBucket: 'upload-92830.appspot.com',
    iosBundleId: 'com.example.foratt',
  );
}
